const gems = [
    { name: "Tailwind", src: "img/equipment/gems/gem-blue.png"},
    { name: "Steel Protection", src: "img/equipment/gems/gem-blue.png"},
    { name: "Ultimate Counter", src: "img/equipment/gems/gem-blue.png"},
    { name: "Brimming Spirit", src: "img/equipment/gems/gem-blue.png"},
    { name: "Perilous Presence", src: "img/equipment/gems/gem-blue.png"},
    { name: "Steelcleaver", src: "img/equipment/gems/gem-red.png"},
    { name: "Accuracte Grace", src: "img/equipment/gems/gem-red.png"},
    { name: "Analyze Weakness", src: "img/equipment/gems/gem-red.png"},
    { name: "Swelling Scourge", src: "img/equipment/gems/gem-red.png"},
    { name: "Refined Incantation", src: "img/equipment/gems/gem-red.png"},
    { name: "Lifebearer", src: "img/equipment/gems/gem-green.png"},
    { name: "Soothing Breath", src: "img/equipment/gems/gem-green.png"},
    { name: "Lifesaving Expertise", src: "img/equipment/gems/gem-green.png"},
    { name: "Swelling Blessing", src: "img/equipment/gems/gem-green.png"},
    { name: "Refined Blessing", src: "img/equipment/gems/gem-green.png"},
    { name: "Ironclad", src: "img/equipment/gems/gem-yellow.png"},
    { name: "Steady Striker", src: "img/equipment/gems/gem-yellow.png"},
    { name: "Doublestrike", src: "img/equipment/gems/gem-yellow.png"},
    { name: "Empowered Combo", src: "img/equipment/gems/gem-yellow.png"},
    { name: "Disperse Bloodlust", src: "img/equipment/gems/gem-yellow.png"},
];

const gemRanks = [
    { name: "Rank I", src: "img/equipment/gems/gem-rank-i.png"},
    { name: "Rank II", src: "img/equipment/gems/gem-rank-ii.png"},
    { name: "Rank III", src: "img/equipment/gems/gem-rank-iii.png"},
    { name: "Rank IV", src: "img/equipment/gems/gem-rank-iv.png"},
    { name: "Rank V", src: "img/equipment/gems/gem-rank-v.png"},
    { name: "Rank VI", src: "img/equipment/gems/gem-rank-vi.png"},
    { name: "Rank VII", src: "img/equipment/gems/gem-rank-vii.png"},
    { name: "Rank VIII", src: "img/equipment/gems/gem-rank-vii.png"},
    { name: "Rank IX", src: "img/equipment/gems/gem-rank-ix.png"},
    { name: "Rank X", src: "img/equipment/gems/gem-rank-x.png"},
];